# Example configuration for continuous monitoring
# Usage: docker compose -f docker-compose.loop.yml up -d

services:
  noaa-alerts:
    build: .
    container_name: noaa-alerts-pushover
    restart: unless-stopped
    volumes:
      - ./config.txt:/app/config.txt:ro
      - ./counties.json:/app/counties.json:ro
      - ./output:/app/output
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      - RUN_MODE=loop
      - CHECK_INTERVAL=90  # Check every 5 minutes (300 seconds)
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Optional: Enable debug mode
    # command: ["--debug"]
