version: '3.8'

services:
  noaa-alerts:
    build: .
    container_name: noaa-alerts-pushover
    restart: unless-stopped
    volumes:
      - ./config.txt:/app/config.txt:ro
      - ./counties.json:/app/counties.json:ro
      - ./output:/app/output
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
    # Optional: Run on a schedule using cron or external scheduler
    # For continuous operation, uncomment the command below:
    # command: sh -c "while true; do python fetch.py && sleep 300; done"
