services:
  noaa-alerts:
    build: .
    container_name: noaa-alerts-pushover
    restart: unless-stopped
    volumes:
      - ./config.txt:/app/config.txt:ro
      - ./counties.json:/app/counties.json:ro
      - ./output:/app/output
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      # Run modes: once, scheduler
      # once: Run once and exit
      # scheduler: Run continuously with Python schedule library (default)
      #            Schedule intervals are configured in config.txt [schedule] section
      - RUN_MODE=scheduler
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Uncomment to pass additional arguments to scheduler.py or fetch.py:
    # command: ["--debug"]
