services:
  noaa-alerts:
    build: .
    container_name: noaa-alerts-pushover
    restart: unless-stopped
    volumes:
      - ./config.txt:/app/config.txt:ro
      - ./counties.json:/app/counties.json:ro
      - ./output:/app/output
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=UTC
      # Run modes: once, loop, cron
      # once: Run once and exit
      # loop: Run continuously with CHECK_INTERVAL seconds between checks (default)
      # cron: Use cron scheduler with CRON_SCHEDULE
      - RUN_MODE=loop
      - CHECK_INTERVAL=300  # Check every 5 minutes (300 seconds)
      # Example cron: */5 * * * * (every 5 minutes)
      # - CRON_SCHEDULE=*/5 * * * *
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Uncomment to pass additional arguments to fetch.py:
    # command: ["--debug"]
